
// AUTH types
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"

export const LOGIN_SUCCESS = "LOGIN_SUCCESS"

export const LOGUT_SUCCESS = "LOGUT_SUCCESS"

export const AUTH_FAIL = "AUTH_FAIL"

export const AUTH_VERIFY = "AUTH_VERIFY"

export const ACTION_FAIL = "ACTION_FAIL"

// book types

export const GET_BOOK_FAIL = "GET_BOOK_FAIL"

export const GET_BOOK_SUCCESS = "GET_BOOK_SUCCESS"

export const RESET_CURRENT = "RESET_CURRENT"

export const SUBTRACT_TO_CURRENT = "SUBTRACT_TO_CURRENT"

export const ADD_TO_CURRENT = "ADD_TO_CURRENT"

export const SET_CURRENT_FAIL = "SET_CURRENT_FAIL"


export const WORD_BOOK_ADD_SUCCESS = "WORD_BOOK_ADD_SUCCESS"

export const WORD_BOOK_ADD_FAIL = "WORD_BOOK_ADD_FAIL"

export const ADD_TO_USER_BOOK = "ADD_TO_USER_BOOK"







